add components for PR
supreeti/Math-magician-App pull request #2
Opened 2023-06-02 15:27 UTC by supreeti

- [ ] Create a new directory called component.
- [ ] Create a new calculator.js file and create a React component.
- [ ] Use functional components and one child component.

2023-06-03 06:54 UTC, divinecharlotte requested changes
Hi @supreeti       , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- descriptive readme 👍 
- Linters are passing 👍 
 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider making sure all the boilerplate that got created by the CRA (*texts*, *images*, and *styles*)are deleted. to make your project clean and related 



_Check the comments under the review._
## Optional suggestions

- 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 06:54 UTC, divinecharlotte commented on src/App.css
> +}
- [ ] kindly consider making sure that your design follows the design snippet you were given in the project requirement to make your design implementation an exact duplicate of the given one  check the images below for more clarrification
- your design 👍 
<img width="927" alt="Screen Shot 2023-06-03 at 08 47 16" src="https://github.com/supreeti/Math-magician-App/assets/60146030/ab00d292-7c03-4c15-babd-30f90a9e3da8">

- given design to implement 👇 
<img width="302" alt="Screen Shot 2023-06-03 at 08 51 59" src="https://github.com/supreeti/Math-magician-App/assets/60146030/1a5b37c1-24f5-4b74-bac9-b3b8c0bbef3f">

2023-06-03 08:54 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @supreeti 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Use React components.
- ✔️ Linters checks are passing
- ✔️ Use Git Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 08:54 UTC, abdulhamiid commented on src/App.css
Your design (It is too small and does not match the given template) 🛠

![image](https://github.com/supreeti/Math-magician-App/assets/78251927/7a062a96-0153-4282-8b17-95b4a0a1176e)

As requested by the previous reviewer, please, create a React component that matches this design: 👀 ✔️ 

![image](https://github.com/supreeti/Math-magician-App/assets/78251927/7720f50e-6e2c-4270-a68a-733954ce5d87)

The Calculator.js component should match the given design: 💪

2023-06-08 11:03 UTC, m05e5 approved these changes
**Hi @supreeti 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights


✔️ Clean Codebase
✔️ You really did great with the UI
✔️ Well done fixing all the linters errors

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-06-08 14:06 UTC, merged